pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
        timestamps()
    }

    stages {

        stage('Checkout') {
            steps {
                cleanWs()
                checkout scm
            }
        }

        stage('Tests') {
            parallel {

                stage('Unit Tests - Backend') {
                    agent {
                        docker {
                            image 'snakee/golang-junit:1.21'
                            reuseNode true
                        }
                    }
                    steps {
                        dir('bugtracker-backend') {
                            sh 'go test -v ./...'
                        }
                    }
                }

                stage('Unit Tests - Frontend') {
                    agent {
                        docker {
                            image 'node:20'
                            reuseNode true
                        }
                    }
                    steps {
                        dir('bugtracker-frontend') {
                            sh '''
                                node --version
                                npm --version

                                npm ci --cache /tmp/npm-cache --prefer-offline

                                npm test

                                echo "=== XML FILES ==="
                                find . -name "*.xml"

                                echo "=== CURRENT DIRECTORY ==="
                                pwd

                                echo "=== FILES ==="
                                ls -la
                        '''
                        }
                    }

                    post {
                        always {
                           junit(
                                testResults: '**/test-results.xml',
                                allowEmptyResults: true
                            )
                             archiveArtifacts(
                                artifacts: '**/test-results.xml',
                                allowEmptyArchive: true
                            )
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}